version: '3.7'

services:
  rabbitmq:
    container_name: "container-rabbitmq-queue"
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './rabbitmq_data:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - queue-live

networks:
  queue-live:
    driver: bridge